### ISSUE TITLE
Port Over Shared Components

### ISSUE THREAD

**Issue by ErikSin** [digidem/react-native-with-mapeo-core-next#37]
## To be ported over
- [x] List Folder
- [x] Touchables Folder
- [x] Add Button
- [x] Animated Radio
- [x] Button
- [x] Centered View *
- [x] Date Distance *
- [ ] GpsPill
- [x] HeaderTitle
- [x] IconButton
- [x] Loading *
- [x] OptionRow
- [x] PhotoView
- [x] Pill
- [x] Select
- [x] Text
- [x] TextButton *
- [x] WifiBar

* indicates component that need to be refactored from `js` to `ts`

## Do not Port over yet:
- Map
- CameraView
- CustomHeaderLeft
- FormattedData
- HomeHeader
- LocationField
- MapThumbnail
- OfflineAreaCard
- OfflineMapLayers
- PasscodeInput
- PracticeMode
- ThumbnailScrollView

**Comment by lightlii** [comment]
@ErikSin If you're ok with it I'm going to use the opportunity to standardise the `sharedComponents` directory structure. Currently we have some of the components in `sharedComponents/ComponentName/index.tsx` and others directly in `sharedComponents/ComponentName.tsx`. It feels a bit messy and since most editors will sort this directory in alphabetical orders it can make things a bit hard to locate at a glance
